title: Shadowsocks Installer
description: Modular Bash installer for Shadowsocks-libev on Ubuntu
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: false

# Custom header image
header-img: /docs/assets/hero.png
